// Generated by CoffeeScript 1.9.2
(function() {
  var client, i, j, parameter, redis;

  redis = require("redis");

  client = redis.createClient();

  parameter = {
    originalImg: "01.jpg"
  };

  for (i = j = 1; j <= 2; i = ++j) {
    parameter.destinalImg = i + ".jpg";
    parameter.resize = {
      width: i,
      height: i
    };
    client.publish("image_process_message#", JSON.stringify(parameter), function(err, res) {
      return console.log(err, res);
    });
  }

}).call(this);
